ALTER TABLE "Campaign"
ADD COLUMN "segmentDays" INTEGER,
ADD COLUMN "priority" INTEGER NOT NULL DEFAULT 2,
ADD COLUMN "maxAttempts" INTEGER NOT NULL DEFAULT 2,
ADD COLUMN "retryIntervalDays" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN "cooldownDays" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN "stopOnBooking" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "stopOnReply" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "restartAfterVisit" BOOLEAN NOT NULL DEFAULT true;
