import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const schema = readFileSync('prisma/schema.prisma', 'utf8')
const route = readFileSync('src/routes/account-management.ts', 'utf8')
const onboarding = readFileSync('src/services/business-onboarding-service.ts', 'utf8')
const ui = readFileSync('src/routes/crm-ui.ts', 'utf8')
const auth = readFileSync('src/routes/auth.ts', 'utf8')

assert.match(schema, /model BusinessPlan/)
assert.match(schema, /model BusinessOnboardingStatus/)
assert.match(schema, /model BusinessBillingSettings/)
assert.match(schema, /model BusinessAccountCharge/)
assert.match(schema, /model BusinessAccountStatusChange/)
assert.match(schema, /enum BusinessDiscountType/)
assert.match(schema, /price\s+Decimal/)
assert.match(schema, /contactPhone\s+String\?/)
assert.match(schema, /contactName\s+String\?/)
assert.match(schema, /firstLoginAt\s+DateTime\?/)
assert.match(route, /ACCOUNT_ROLES = new Set\(\['SUPER_ADMIN', 'ACCOUNT_ADMIN'\]\)/)
assert.match(route, /accountAdminId: request\.auth!\.user\.id/)
assert.match(route, /createdByUserId: request\.auth!\.user\.id/)
assert.match(route, /workspaceBusiness/)
assert.match(route, /app\.patch\('\/admin\/accounts\/:id'/)
assert.match(route, /app\.patch\('\/admin\/account-plans\/:id'/)
assert.match(route, /charges\/:chargeId\/payment/)
assert.match(route, /charges\/:chargeId\/bonification/)
assert.match(route, /charges\/:chargeId\/due-date/)
assert.match(route, /accounts\/:id\/status/)
assert.match(route, /resolveAccountStatusTransition/)
assert.match(route, /Solo el Super Admin puede reactivar una cuenta cancelada/)
assert.match(route, /Configura un plan con precio antes de activar la cuenta/)
assert.match(route, /await Promise\.all\(\[/)
assert.doesNotMatch(route, /setInterval|cron|24 \* 60/)
assert.match(onboarding, /refreshBusinessOnboarding/)
assert.match(onboarding, /hasServices/)
assert.match(onboarding, /whatsappConnected/)
assert.match(auth, /firstLoginAt/)
assert.match(auth, /data: \{ role: 'ACCOUNT_ADMIN', canCreateBusinesses: true \}/)
assert.doesNotMatch(auth, /data: \{ canCreateBusinesses: true \}/)
assert.match(ui, /data-section="accounts"/)
assert.match(ui, /\/admin\/accounts\?/)
assert.match(ui, /id="account-contact-phone"/)
assert.match(ui, /id="account-plan"/)
assert.match(ui, /data-enter-managed-account/)
assert.match(ui, /support-return-accounts/)
assert.match(ui, /data-edit-managed-account/)
assert.match(ui, /id="account-billing-day"/)
assert.match(ui, /id="account-billing-month"/)
assert.match(ui, /Configurar planes/)
assert.match(ui, /Registrar transferencia/)
assert.match(ui, /No pudimos cargar las cuentas en este momento/)
assert.match(ui, /data-account-status-action/)
assert.match(ui, /Historial de estado/)
assert.doesNotMatch(ui, /id="account-edit-status"/)
assert.match(ui, /state\.businessId = state\.business\?\.id \|\| null\s+\/\/ El menu inicial[\s\S]*?hydrateWorkspaceNav\(\)/)

console.log('Account management contract tests passed')
