import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
const route = readFileSync('src/routes/demo-profile.ts', 'utf8')
const ui = readFileSync('src/routes/crm-ui.ts', 'utf8')
const store = readFileSync('src/conversational-bot/demo-preview-prisma.ts', 'utf8')
const preview = route.slice(route.indexOf("if (body.mode === 'conversational-preview')"), route.indexOf('const phone = `demo:${user.id}:${sessionId}`'))
assert.match(route, /body.mode !== 'existing'/, 'explicit existing mode must preserve the original simulator')
assert.match(preview, /user.role !== 'SUPER_ADMIN' \|\| business.demoType !== 'QA_SANDBOX'/)
assert.match(preview, /runPrismaDemoPreview/)
assert.match(store, /demo:preview:/)
assert.match(store, /FOR UPDATE/)
assert.match(store, /supportBotState/)
assert.match(store, /timeout: 10_000/)
assert.doesNotMatch(preview, /runDeterministicDemoSimulation|conversationService|publishConversation|reopenClosedConversationOpportunity|appointment\.create|outbox|webhook/i)
assert.match(ui, /id="demo-preview-mode"/)
assert.match(ui, /demo-preview-mode\[hidden\] \{ display: none; \}/)
assert.match(ui, /grid-template-rows: auto auto auto minmax\(0, 1fr\) auto/)
assert.match(ui, /demoPreviewModeRow\.hidden = !eligible/)
assert.match(ui, /els\.demoPreviewMode\.value = 'existing'/)
assert.match(ui, /mode: els\.demoPreviewMode\.value/)
assert.match(ui, /Datos entendidos y tiempos/)
assert.match(ui, /escapeHtml\(JSON\.stringify\(message\.preview/)
console.log('conversational preview wiring: OK')
