import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const ui = await readFile('src/routes/crm-ui/cash-register.ts', 'utf8')

assert.match(ui, /id="cash-product-catalog-open"/)
assert.match(ui, /id="cash-product-sale-open"/)
assert.match(ui, /id="cash-product-catalog-dialog"/)
assert.match(ui, /id="cash-product-category-form"/)
assert.match(ui, /id="cash-product-form"/)
assert.match(ui, /id="cash-product-sale-dialog"/)
assert.match(ui, /id="cash-product-sale-items"/)
assert.match(ui, /id="appointment-product-items"/)
assert.match(ui, /Productos comprados/)
assert.match(ui, /getJson\(cashScoped\('\/products'/)
assert.match(ui, /getJson\(cashScoped\('\/product-categories'/)
assert.match(ui, /cashCollection\(categoriesResult\.value, 'categories'\)/)
assert.match(ui, /cashCollection\(productsResult\.value, 'products'\)/)
assert.match(ui, /Array\.isArray\(payload\?\.\[collectionKey\]\)/)
assert.match(ui, /Promise\.allSettled/)
assert.match(ui, /No pudimos cargar las categor&iacute;as/)
assert.match(ui, /No pudimos cargar los productos/)
assert.match(ui, /renderCashProductCatalog\(\)[\s\S]*await loadCashProducts\(\)/)
assert.match(ui, /getJson\('\/product-sales'/)
assert.match(ui, /getJson\('\/appointments\/' \+ encodeURIComponent\(appointmentId\) \+ '\/product-items'/)
assert.match(ui, /productId, quantity/)
assert.match(ui, /cashSessionId/)
assert.match(ui, /paymentMethod/)
assert.match(ui, /salePrice/)
assert.match(ui, /id="cash-product-description"/)
assert.match(ui, /id="cash-product-sort-order"/)
assert.match(ui, /id="cash-product-category-sort-order"/)
assert.match(ui, /id="cash-product-sale-discount"/)
assert.match(ui, /discountAmount/)
assert.match(ui, /idempotencyKey/)
assert.match(ui, /crypto\.randomUUID/)
assert.match(ui, /method: 'PATCH'[\s\S]*quantity/)
assert.match(ui, /appointment-finance-service-subtotal/)
assert.match(ui, /appointment-finance-product-subtotal/)
assert.match(ui, /Sin controlar stock/)
assert.match(ui, /Precio unitario/)
assert.match(ui, /Cliente opcional/)
assert.match(ui, /No env&iacute;a ni cobra autom&aacute;ticamente/)
assert.doesNotMatch(ui, /\b(?:alert|confirm|prompt)\s*\(/)

console.log('OK UI de productos: cat&aacute;logo, categor&iacute;as, venta directa y productos en turno')
