import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { workshopJobsMarkup, workshopJobsScript } from '../src/routes/workshop-jobs-ui.js'
assert.match(workshopJobsScript, /localStorage\.setItem\('workshop-job-dialog-size'/)
assert.match(workshopJobsScript, /new ResizeObserver/)
assert.match(workshopJobsMarkup, /--wj-field-height/)
assert.match(workshopJobsScript, /Math\.max\(width\/baseWidth,height\/baseHeight\)/)
for (const token of ['--wj-scale', 'calc(19px * var(--wj-scale))', 'calc(12px * var(--wj-scale))', 'calc(20px * var(--wj-scale))']) assert.ok(workshopJobsMarkup.includes(token), token)
assert.doesNotMatch(workshopJobsScript, /wj\('backdrop'\)\.addEventListener\('click'/)
assert.match(workshopJobsScript, /wjCatalog=\[\]/)
assert.doesNotMatch(workshopJobsScript, /wjBasics|data-wj-basic/)
assert.match(workshopJobsMarkup, /id="wj-sc-remove"/)
assert.match(workshopJobsMarkup, /id="wj-sc-status"/)
assert.doesNotMatch(workshopJobsMarkup + workshopJobsScript, /wj-sc-new|wj\('sc-new'\)|\(oculto\)/)
assert.match(workshopJobsScript, /wj\('config-list'\)\.innerHTML = wjCatalog\.filter\(x=>x.active\)/)
console.log('Workshop job dialog contract: OK')
assert.match(workshopJobsScript, /row\.dataset\.wjRow=String\(index\)/)
assert.match(workshopJobsScript, /closest\('\[data-wj-row\]'\)/)
assert.match(workshopJobsScript, /host\.onkeydown/)
const crmUi = readFileSync('src/routes/crm-ui.ts','utf8')
for (const marker of ['id="wp-backdrop"','id="wp-form"','id="wp-page-list"','id="wp-add"','workshop-personnel','Personal','Dar de baja','Reactivar']) assert.ok((workshopJobsMarkup + workshopJobsScript + crmUi).includes(marker),marker)
for (const spacing of ['#wp-backdrop .wj-header{padding:22px 26px 18px}', '.wp-body{min-height:0;padding:26px', '.wp-editor{display:grid;gap:22px}']) assert.ok(workshopJobsMarkup.includes(spacing),spacing)
assert.doesNotMatch(crmUi, /id="wp-open"|Administrar trabajadores/)
assert.match(workshopJobsScript, /includeInactive=1/)
assert.match(workshopJobsScript, /wpItems\.filter\(x=>x\.active\)/)
assert.match(workshopJobsMarkup, /<select id="wj-responsible" required>/)
assert.doesNotMatch(workshopJobsMarkup, /Eleg&iacute; o escrib&iacute; un nombre|<datalist id="wj-performers">/)
assert.match(workshopJobsScript, /performerId:wj\('responsible'\)\.value/)
assert.match(workshopJobsScript, /Sin registro/)
assert.match(crmUi, /id="wj-filter-performer"/)
assert.match(workshopJobsScript, /limit=10&offset=/)
assert.match(workshopJobsScript, /Cargando trabajos anteriores/)
assert.match(workshopJobsScript, /No hay m&aacute;s trabajos anteriores/)
assert.match(workshopJobsScript, /addEventListener\('scroll'/)
assert.match(crmUi, /border-bottom: 2px solid #b8c4d4/)
