import assert from 'node:assert/strict'
import { parseWorkshopJob, parseWorkshopShortcut } from '../src/services/workshop-job-domain.js'
import { workshopDefaultShortcuts } from '../src/services/workshop-shortcuts.js'
import { calculateWorkshopMaintenance, presentWorkshopMaintenance, shouldReplaceWorkshopMaintenance } from '../src/services/workshop-maintenance.js'
const input = { vehicleId: 'v', date: '2026-09-07', mileage: 85000, performerId: 'performer-a', lines: [{ description: 'Aceite', quantity: 2, parts: '10', labor: '' }] }
const job = parseWorkshopJob(input)
assert.equal(job.performerId, 'performer-a')
assert.equal(job.lines[0]?.partsCents, 1000)
assert.equal(job.totalCents, 2000)
assert.equal(parseWorkshopJob({...input,lines:[{description:'Aceite',quantity:1,parts:'12500',labor:''}]}).totalCents,1_250_000)
assert.equal(job.lines[0]?.laborCents, null)
assert.throws(() => parseWorkshopJob({...input,lines:[{...input.lines[0],parts:'10,50'}]}))
const linkedJob=parseWorkshopJob({...input,lines:[{...input.lines[0],serviceId:'service-a',nextDueDate:'2027-03-07',nextDueMileage:96000}]})
assert.equal(linkedJob.lines[0]?.serviceId,'service-a')
assert.equal(linkedJob.lines[0]?.nextDueDate,'2027-03-07')
assert.equal(linkedJob.lines[0]?.nextDueMileage,96000)
assert.throws(()=>parseWorkshopJob({...input,lines:[{...input.lines[0],serviceId:'service-a',nextDueDate:'2026-02-30'}]}))
for (const invalid of [{date:'2026-02-30'}, {mileage:-1}, {performerId:''}, {lines:[]}, {lines:[{description:'x',quantity:0}]}, {lines:[{description:'x',quantity:1,parts:'abc'}]}]) assert.throws(() => parseWorkshopJob({...input,...invalid}))
const trackedService=parseWorkshopShortcut({name:' Filtro ',description:'Cambio de filtro',quantity:1,recurrenceEnabled:true,returnMonths:6,returnKilometers:10000,customerInstructions:'Controlar el nivel'})
assert.equal(trackedService.name,'Filtro')
assert.equal(trackedService.recurrenceEnabled,true)
assert.equal(trackedService.returnMonths,6)
assert.equal(trackedService.returnKilometers,10000)
assert.equal(trackedService.customerInstructions,'Controlar el nivel')
assert.equal(parseWorkshopShortcut({name:'Diagnóstico',description:'Revisión',quantity:1}).recurrenceEnabled,false)
assert.throws(() => parseWorkshopShortcut({name:'Aceite',description:'Cambio',quantity:1,recurrenceEnabled:true}))
assert.throws(() => parseWorkshopShortcut({name:'Aceite',description:'Cambio',quantity:1,returnMonths:0}))
assert.throws(() => parseWorkshopShortcut({name:'Aceite',description:'Cambio',quantity:1,returnKilometers:1000001}))
assert.throws(() => parseWorkshopShortcut({name:'',description:'x'}))
assert.deepEqual(workshopDefaultShortcuts('business-a').map(item=>item.name),['Cambio de aceite','Filtro de aceite','Filtro de aire','Filtro de habitáculo','Filtro de combustible','Engrase','Correa de distribución','Líquido refrigerante'])
const calculated=calculateWorkshopMaintenance({jobDate:'2026-09-07',jobMileage:85000,line:{serviceId:'service-a'},service:{id:'service-a',name:'Cambio de aceite',recurrenceEnabled:true,returnMonths:6,returnKilometers:10000,customerInstructions:'Revisar nivel'}})
assert.equal(calculated?.nextDueDate,'2027-03-07')
assert.equal(calculated?.nextDueMileage,95000)
assert.equal(calculated?.manuallyAdjusted,false)
const relative=calculateWorkshopMaintenance({jobDate:'2026-09-07',jobMileage:85000,line:{serviceId:'service-a',returnMonths:9,returnKilometers:5000},service:{id:'service-a',name:'Cambio de aceite',recurrenceEnabled:true,returnMonths:6,returnKilometers:10000,customerInstructions:'Revisar nivel'}})
assert.equal(relative?.returnMonths,9)
assert.equal(relative?.returnKilometers,5000)
assert.equal(relative?.nextDueDate,'2027-06-07')
assert.equal(relative?.nextDueMileage,90000)
assert.equal(relative?.manuallyAdjusted,true)
const withoutKm=calculateWorkshopMaintenance({jobDate:'2026-01-31',jobMileage:85000,line:{serviceId:'service-a',returnMonths:1,returnKilometers:null},service:{id:'service-a',name:'Cambio de aceite',recurrenceEnabled:true,returnMonths:6,returnKilometers:10000,customerInstructions:''}})
assert.equal(withoutKm?.nextDueDate,'2026-02-28')
assert.equal(withoutKm?.nextDueMileage,null)
const relativeJob=parseWorkshopJob({...input,lines:[{...input.lines[0],serviceId:'service-a',returnMonths:9,returnKilometers:5000}]})
assert.equal(relativeJob.lines[0]?.returnMonths,9)
assert.equal(relativeJob.lines[0]?.returnKilometers,5000)
const overridden=calculateWorkshopMaintenance({jobDate:'2026-09-07',jobMileage:85000,line:{serviceId:'service-a',nextDueDate:'2027-04-10',nextDueMileage:97000},service:{id:'service-a',name:'Cambio de aceite',recurrenceEnabled:true,returnMonths:6,returnKilometers:10000,customerInstructions:'Revisar nivel'}})
assert.equal(overridden?.nextDueDate,'2027-04-10')
assert.equal(overridden?.nextDueMileage,97000)
assert.equal(overridden?.manuallyAdjusted,true)
assert.equal(calculateWorkshopMaintenance({jobDate:'2026-09-07',jobMileage:85000,line:{serviceId:'service-a'},service:{id:'service-a',name:'Diagnóstico',recurrenceEnabled:false,returnMonths:null,returnKilometers:null,customerInstructions:''}}),null)
const maintenanceView=presentWorkshopMaintenance([
  {id:'c1',serviceId:'s1',serviceName:'Aceite',lastPerformedDate:'2026-03-01',lastMileage:80000,nextDueDate:'2026-09-01',nextDueMileage:90000,customerInstructions:'Revisar nivel'},
  {id:'c2',serviceId:'s2',serviceName:'Refrigerante',lastPerformedDate:'2026-01-01',lastMileage:70000,nextDueDate:'2027-01-01',nextDueMileage:null,customerInstructions:''}
],85000,new Date('2026-09-21T12:00:00Z'))
assert.equal(maintenanceView.items[0]?.status,'OVERDUE')
assert.equal(maintenanceView.items[1]?.status,'UP_TO_DATE')
assert.equal(maintenanceView.summary.overdue,1)
assert.equal(shouldReplaceWorkshopMaintenance('2026-09-20','2026-09-01'),false)
assert.equal(shouldReplaceWorkshopMaintenance('2026-09-01','2026-09-20'),true)
assert.equal(shouldReplaceWorkshopMaintenance('2026-09-20','2026-09-20'),true)
console.log('Workshop jobs domain: OK')
