import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { workshopJobsMarkup, workshopJobsScript } from '../src/routes/workshop-jobs-ui.js'
assert.match(workshopJobsScript, /localStorage\.setItem\('workshop-job-dialog-size'/)
assert.match(workshopJobsScript, /new ResizeObserver/)
assert.match(workshopJobsMarkup, /--wj-field-height/)
assert.match(workshopJobsScript, /Math\.max\(width\/baseWidth,height\/baseHeight\)/)
for (const token of ['--wj-scale', 'calc(19px * var(--wj-scale))', 'calc(12px * var(--wj-scale))', 'calc(20px * var(--wj-scale))']) assert.ok(workshopJobsMarkup.includes(token), token)
assert.doesNotMatch(workshopJobsScript, /wj\('backdrop'\)\.addEventListener\('click'/)
assert.match(workshopJobsScript, /wjCatalog=\[\]/)
assert.doesNotMatch(workshopJobsScript, /wjBasics|data-wj-basic/)
assert.doesNotMatch(workshopJobsMarkup + workshopJobsScript, /id="wj-config-toggle"|id="wj-config-list"|id="wj-sc-save"|wj\('config-toggle'\)/)
assert.match(workshopJobsScript, /wsLoad/)
assert.match(workshopJobsScript, /wsReturnLabel/)
assert.match(workshopJobsScript, /data-ws-edit/)
console.log('Workshop job dialog contract: OK')
assert.match(workshopJobsScript, /row\.dataset\.wjRow=String\(index\)/)
assert.match(workshopJobsScript, /closest\('\[data-wj-row\]'\)/)
assert.match(workshopJobsScript, /host\.onkeydown/)
const crmUi = readFileSync('src/routes/crm-ui.ts','utf8')
for (const marker of ['id="wp-backdrop"','id="wp-form"','id="wp-page-list"','id="wp-add"','workshop-personnel','Personal','Dar de baja','Reactivar','id="ws-backdrop"','id="ws-form"','id="ws-page-list"','id="ws-add"','workshop-services','Servicios']) assert.ok((workshopJobsMarkup + workshopJobsScript + crmUi).includes(marker),marker)
for (const spacing of ['#wp-backdrop .wj-header,#ws-backdrop .wj-header{padding:22px 26px 18px}', '.wp-body{min-height:0;padding:26px', '.wp-editor{display:grid;gap:22px}']) assert.ok(workshopJobsMarkup.includes(spacing),spacing)
assert.doesNotMatch(crmUi, /id="wp-open"|Administrar trabajadores/)
assert.match(workshopJobsScript, /serviceId/)
assert.match(workshopJobsScript, /nextDueDate/)
assert.match(workshopJobsScript, /nextDueMileage/)
assert.match(workshopJobsScript, /wjAddMonths/)
assert.match(workshopJobsMarkup + workshopJobsScript + crmUi, /returnMonths/)
assert.match(workshopJobsMarkup + workshopJobsScript + crmUi, /returnKilometers/)
assert.match(workshopJobsMarkup + workshopJobsScript + crmUi, /customerInstructions/)
assert.match(workshopJobsScript, /includeInactive=1/)
assert.match(workshopJobsScript, /wpItems\.filter\(x=>x\.active\)/)
assert.match(workshopJobsMarkup, /<select id="wj-responsible" required>/)
assert.doesNotMatch(workshopJobsMarkup, /Eleg&iacute; o escrib&iacute; un nombre|<datalist id="wj-performers">/)
assert.match(workshopJobsScript, /performerId:wj\('responsible'\)\.value/)
assert.match(workshopJobsScript, /Sin registro/)
assert.match(crmUi, /id="wj-filter-performer"/)
assert.match(workshopJobsScript, /wj\('filter-date'\)\.value=wjDateToday\(\)/)
assert.match(workshopJobsScript, /limit=10&offset=/)
assert.match(workshopJobsScript, /const wjAllHistory=.*pageSize:20/)
assert.match(workshopJobsScript, /limit=\x27\+wjAllHistory\.pageSize\+\x27&offset=\x27\+offset/)
assert.match(workshopJobsScript, /wj-page-prev/)
assert.match(workshopJobsScript, /wj-page-next/)
assert.match(workshopJobsScript, /wjAllHistory\.offset=0/)
assert.match(workshopJobsScript, /requestId:\s*0/)
assert.match(workshopJobsScript, /requestId!==wjAllHistory\.requestId/)
for (const marker of ['id="wj-page-controls"','id="wj-page-prev"','id="wj-page-status"','id="wj-page-next"']) assert.ok(crmUi.includes(marker),marker)
assert.match(workshopJobsScript, /Cargando trabajos anteriores/)
assert.match(workshopJobsScript, /No hay m&aacute;s trabajos anteriores/)
assert.match(workshopJobsScript, /addEventListener\('scroll'/)
assert.match(crmUi, /border-bottom: 2px solid #b8c4d4/)
assert.ok(crmUi.includes("'\/maintenance?businessId=' + encodeURIComponent(state.businessId)"))
assert.ok(crmUi.includes('renderWorkshopMaintenance(maintenance) +'))
assert.match(crmUi, /workshop-maintenance-list/)
assert.match(crmUi, /id="ws-public-url"/)
assert.match(crmUi, /id="ws-public-save"/)
assert.match(workshopJobsScript, /\/workshop\/settings/)
assert.match(crmUi, /data-workshop-qr/)
assert.match(crmUi, /openWorkshopQr/)
assert.match(crmUi, /workshop-qr-printing/)
